branches:
  only:
    - master
language: node_js
node_js:
- lts/*
git:
  depth: 3
install:
- yarn --frozen-lockfile
script:
- sh ./release.sh
after_success:
- GREN_GITHUB_TOKEN=$GITHUB_TOKEN yarn release
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=$DINGTALK_ROBOT_TOKEN
# after_script:
# - sh ./notify.sh
cache: yarn